name: ${project.artifactId}
main: ${mainClass}
version: ${project.version}
load: POSTWORLD
author: ${author}
depend: [AdvancedReplay]
softdepend: [Vulcan, Spartan, Matrix, GodsEye, Atlas, Kauri, Karhu, KarhuAPI, Themis, Soaroma, FlappyAnticheat, OreAnnouncer, AntiCheatReloaded, Artemis, Verus, VerusAPI, Intave, Sparky, LightAntiCheat, AntiHaxerman, GrimAC, Reflex]
api-version: 1.13
commands:
  replayreload:
      description: Reload config
  report:
      description: Report a player of suspected hacks