- uses: cloudnode-pro/modrinth-publish@v2
  with:
    token: ${{ secrets.MODRINTH_TOKEN }}
    project: KX9g44hM
    version: 1.2.3
    loaders: paper
    game-versions: 1.21.11
    files: target/AntiCheatReplay-1.2.3.jar
